site:
  title: The Internals of Apache Spark
  url: http://books.japila.pl/apache-spark-internals
  start_page: apache-spark-internals::book-intro.adoc
content:
  sources:
  - url: .
    branches: HEAD
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

